version: "3.1"
services:
  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw

    webserver:
      - ./dbt:/usr/local/airflow/dbt:rw

    triggerer:
      - ./dbt:/usr/local/airflow/dbt:rw